name: Build and Deploy Static Pages

on:
  push:
    branches: [ master ]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v2.3.1
      with:
        # persist-credentials: false
        submodules: true

    - name: Node Environment ğŸ”§
      uses: actions/setup-node@v1
      with:
        node-version: 12

      #run: |
      #  docker run \
      #  -v ${{ github.workspace }}:/srv/jekyll \
      #  -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
      #  jekyll/builder:latest /bin/bash \
      #  -c "chmod 777 /srv/jekyll && jekyll build --future"
      #

    - name: Build Static Site ğŸ”§
      run: |
        npm install
        npm run-script build

      # run: npm ci
      # run: npm test
      # run: npm run build
      #
      # uses: chabad360/hugo-actions@master
      # with:
      #   buildPath: 'public'
      #   args: --gc --minify --cleanDestinationDir
      #

    - name: Deploy ğŸš€
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _site
        CLEAN: true
        COMMIT_MESSAGE: 'Publishing'

      # Cecilapp/GitHub-Pages-deploy
      # env:
      #   GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #   BUILD_DIR: _site
      #   #JEKYLL_SITE: NO or YES
      #   EMAIL: kaceong@gmail.com
      #   CNAME: www.kaceong.com
